#!/usr/bin/env bash
# Bash script that transfers a file from our client to a servev using scp

path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_SOURCE")
brown='\e[0;33m'
reset='\033[0m'
if [ "$#" -lt 4 ]; then
    echo -e "Usage: ${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$path"/"$1" "$3"@"$2":/home/"$3"/
fi
