#!/usr/bin/env bash
# configure a load-balancing server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy=1.8.\*

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend web_back
backend web_back
	mode http
	balance roundrobin
	server 447962-web-01 34.202.234.181:80 check
	server 447962-web-02 54.173.84.105:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
