#!/usr/bin/env bash
# Accepts a string as an argument. Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed. Ping the IP address 5 times

if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

if ping -c 5 "$1"; then
    :
else
    :
fi
