#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.
# Check if an argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the provided IP address 5 times
ping -c 5 "$1"
