#!/usr/bin/env bash
#This script displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line using while loop

i=1
while [ $i -lt 11 ]
do
    if [ $i -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i+1))
done