#!/usr/bin/env bash
# This script creates an RSA key pair.
# The public key is saved in the file ~/.ssh/holberton
# The private key is saved in the file ~/.ssh/holberton
private_key="school"
passphrase="betty"

ssh-keygen -b 4096 -f "$private_key" -N "$passphrase"
